### ISSUE TITLE
Structural name + abbreviation: MathUtil

### ISSUE THREAD

**Issue by jbrains** [angellaa/Fraction#2]
I notice that you've named the class `MathUtil`, which is a structural name ("Util") and an abbreviation (instead of "Utilities"). I would prefer to rename this class. After several iterations, I chose `NumberTheory`.

Yes, I know that "Util" is a common abbreviation, and I sometimes use common abbreviations, but only when everyone around me insists on it. If I wanted this class to remain named "Something Something Utilities", and if the people around me insisted on calling it `SomethingSomethingUtil`, I would fight them for maybe 15-30 seconds. I would ask, "Why is `Util` so much better than `Utilities` and what's the problem with `Utilities`?"

For the bigger issue, I prefer to replace the structural name (this object has utility functions related to math) with a more intention-revealing or domain-oriented name (this namespace has behavior related to number theory). That's why I choose `NumberTheory` (and not `NumberTheoryUtilities`). I suppose, if Java didn't already have a namespace called `Math`, I might use the name `Math`, but I like the more specific name `NumberTheory`. (I would rename `Math` to `Arithmetic` for functions like `power()` and `abs()` or to `Statistics` for `min()` and `max()` and `average()`.)

**Comment by angellaa** [comment]
I understand your reasoning and it make sense.
